version: '3'

services:
  db:
    image: postgres:11-alpine
    env_file:
      - .env
    volumes:
      - ./postgresql/dumps:/code/dumps
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"